import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import Navbar from "../Components/Navbar";
import { CartProvider } from "@/Components/CartContext";

const geistSans = localFont({
    src: "./fonts/GeistVF.woff",
    variable: "--font-geist-sans",
    weight: "100 900",
});
const geistMono = localFont({
    src: "./fonts/GeistMonoVF.woff",
    variable: "--font-geist-mono",
    weight: "100 900",
});

export const metadata: Metadata = {
    title: "DevLights Clase 8",
    description: "Generated by create next app",
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <CartProvider>
            <html lang="es">
                <body
                    className={`${geistSans.variable} ${geistMono.variable} antialiased flex flex-col min-h-screen min-w-screen justify-center content-between`}
                >
                    <header>
                        <Navbar />
                    </header>
                    <main className="w-full flex justify-center">
                        {children}
                    </main>
                </body>
            </html>
        </CartProvider>
    );
}
